"""
Test the error detection model on real-world user issues.
Evaluates accuracy and identifies incorrect predictions.
"""

from pathlib import Path
import sys
import io
import json
from typing import Dict, List, Tuple

# Fix Windows console encoding
if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

HERE = Path(__file__).parent.resolve()

# Real-world issues with expected error types
REAL_WORLD_ISSUES = {
    # POWER / STARTUP ISSUES (1-60)
    "My PC not turning on": "PSU / Power Issue",
    "Computer no power": "PSU / Power Issue",
    "PC dead suddenly": "PSU / Power Issue",
    "Power button not working": "PSU / Power Issue",
    "PC not start after power cut": "PSU / Power Issue",
    "PC start then off": "PSU / Power Issue",
    "Computer restart again again": "PSU / Power Issue",
    "PC stuck black screen": "No Display / No Signal",
    "Nothing show on monitor": "No Display / No Signal",
    "PC fan spin but no display": "No Display / No Signal",
    "Laptop not start": "Windows Boot Failure",
    "PC light on but screen black": "No Display / No Signal",
    "PC not boot": "Windows Boot Failure",
    "Computer stuck at logo": "Windows Boot Failure",
    "PC shutdown suddenly": "PSU / Power Issue",
    "System not starting": "Windows Boot Failure",
    "PC start slow then off": "PSU / Power Issue",
    "Laptop dead no charging": "PSU / Power Issue",
    "PC no response": "PSU / Power Issue",
    "Power supply problem maybe": "PSU / Power Issue",
    "PC restart loop": "Windows Boot Failure",
    "PC start beep sound": "RAM Upgrade",  # Beep codes often indicate RAM
    "Computer not wake up": "Windows Boot Failure",
    "PC on but keyboard light off": "Windows Boot Failure",
    "Monitor on but PC not": "PSU / Power Issue",
    "PC off when press power": "PSU / Power Issue",
    "Laptop power light blink": "PSU / Power Issue",
    "PC not start after update": "Windows Boot Failure",
    "Computer stuck booting": "Windows Boot Failure",
    "PC no signal": "No Display / No Signal",
    "PC stuck loading": "Windows Boot Failure",
    "Computer not boot after clean": "Windows Boot Failure",
    "PC restart when login": "Windows Boot Failure",
    "PC start but freeze": "Windows Boot Failure",
    "System not responding on start": "Windows Boot Failure",
    "PC turn on late": "PSU / Power Issue",
    "Laptop not power on": "PSU / Power Issue",
    "PC power on delay": "PSU / Power Issue",
    "Computer start randomly": "PSU / Power Issue",
    "PC not turn off properly": "Windows Boot Failure",
    "PC fail to start": "Windows Boot Failure",
    "System not booting": "Windows Boot Failure",
    "Laptop not charging": "PSU / Power Issue",
    "PC on then blank": "No Display / No Signal",
    "PC crash on startup": "Windows Boot Failure",
    "Boot problem error": "Windows Boot Failure",
    "PC start noise then off": "PSU / Power Issue",
    "Laptop auto shutdown": "PSU / Power Issue",
    "Computer power issue": "PSU / Power Issue",
    "PC start only sometimes": "PSU / Power Issue",
    "Power issue after rain": "PSU / Power Issue",
    "PC dead after voltage drop": "PSU / Power Issue",
    "PC power flicker": "PSU / Power Issue",
    "Computer restart when plug charger": "PSU / Power Issue",
    "Laptop power drain fast": "PSU / Power Issue",
    "PC stuck at BIOS": "Windows Boot Failure",
    "BIOS open only": "Windows Boot Failure",
    "PC stuck startup repair": "Windows Boot Failure",
    "Laptop battery not detect": "PSU / Power Issue",
    "PC start but nothing works": "Windows Boot Failure",
    
    # PERFORMANCE / SLOW ISSUES (61-120)
    "My PC very slow": "Slow Performance",
    "Computer hang always": "Slow Performance",
    "PC lag too much": "Slow Performance",
    "Everything freeze suddenly": "Slow Performance",
    "PC slow after update": "Slow Performance",
    "System slow when open apps": "Slow Performance",
    "Laptop slow even small work": "Slow Performance",
    "PC slow boot": "SSD Upgrade",
    "PC slow after few minutes": "Slow Performance",
    "Computer hang when multitask": "RAM Upgrade",
    "Mouse move slow": "Slow Performance",
    "Keyboard delay": "Slow Performance",
    "PC slow with internet": "Slow Performance",
    "Laptop slow when charging": "Slow Performance",
    "PC lag while typing": "Slow Performance",
    "System freeze randomly": "Slow Performance",
    "PC slow opening files": "SSD Upgrade",
    "Computer not smooth": "Slow Performance",
    "PC delay click response": "Slow Performance",
    "Laptop hang when browser open": "RAM Upgrade",
    "PC slow with games": "GPU Upgrade",
    "System stutter problem": "Slow Performance",
    "PC lag when start": "SSD Upgrade",
    "Computer freeze screen": "Slow Performance",
    "PC slow suddenly": "Slow Performance",
    "Laptop heat and slow": "CPU Overheat",
    "PC slow with antivirus": "Slow Performance",
    "PC slow after software install": "Slow Performance",
    "Computer lag on startup": "SSD Upgrade",
    "PC not responding error": "Slow Performance",
    "Laptop freeze after sleep": "Slow Performance",
    "PC lag on windows": "Slow Performance",
    "PC slow loading programs": "SSD Upgrade",
    "System slow overall": "Slow Performance",
    "PC hang often": "Slow Performance",
    "Laptop slow boot time": "SSD Upgrade",
    "PC slow performance": "Slow Performance",
    "System lag spike": "Slow Performance",
    "PC stutter randomly": "Slow Performance",
    "PC freeze when idle": "Slow Performance",
    "Laptop lag on video": "GPU Upgrade",
    "PC slow when copy files": "SSD Upgrade",
    "PC lag with USB": "USB / Port Issue",
    "Computer slow on battery": "Slow Performance",
    "PC delay shutdown": "Slow Performance",
    "System hang on login": "Slow Performance",
    "PC lag scrolling": "Slow Performance",
    "Laptop slow browsing": "RAM Upgrade",
    "PC performance drop": "Slow Performance",
    "Computer slow after long use": "Slow Performance",
    "PC lag background apps": "RAM Upgrade",
    "PC freeze mouse only": "Slow Performance",
    "Laptop stutter sound": "Slow Performance",
    "PC slow with updates": "Slow Performance",
    "PC lag opening folders": "SSD Upgrade",
    "System slow suddenly": "Slow Performance",
    "PC delay everything": "Slow Performance",
    "Laptop hang random": "Slow Performance",
    "PC very unresponsive": "Slow Performance",
    "System sluggish": "Slow Performance",
    
    # RAM / MEMORY ISSUES (121-180)
    "PC slow after adding RAM": "RAM Upgrade",
    "RAM not detected": "RAM Upgrade",
    "PC beep sound": "RAM Upgrade",
    "PC blue screen after RAM": "Blue Screen (BSOD)",
    "System crash when multitask": "RAM Upgrade",
    "PC restart when open apps": "RAM Upgrade",
    "RAM issue maybe": "RAM Upgrade",
    "PC freeze after some time": "RAM Upgrade",
    "Computer not boot after RAM change": "RAM Upgrade",
    "PC stuck after RAM upgrade": "RAM Upgrade",
    "RAM slot problem": "RAM Upgrade",
    "Memory error message": "RAM Upgrade",
    "PC hang after install RAM": "RAM Upgrade",
    "Laptop RAM not showing": "RAM Upgrade",
    "System crash heavy use": "RAM Upgrade",
    "PC restart randomly": "RAM Upgrade",
    "RAM mismatch problem": "RAM Upgrade",
    "PC boot fail RAM": "RAM Upgrade",
    "Memory usage high": "RAM Upgrade",
    "PC slow memory issue": "RAM Upgrade",
    "RAM problem after clean": "RAM Upgrade",
    "Laptop lag RAM": "RAM Upgrade",
    "PC freeze open browser": "RAM Upgrade",
    "Memory error popup": "RAM Upgrade",
    "PC restart after RAM touch": "RAM Upgrade",
    "RAM loose problem": "RAM Upgrade",
    "System not stable RAM": "RAM Upgrade",
    "PC crash gaming RAM": "RAM Upgrade",
    "RAM speed issue": "RAM Upgrade",
    "Laptop RAM upgrade fail": "RAM Upgrade",
    "PC no display RAM": "RAM Upgrade",
    "Memory slot not working": "RAM Upgrade",
    "PC beep continuous": "RAM Upgrade",
    "PC hang after boot": "RAM Upgrade",
    "Laptop RAM heating": "RAM Upgrade",
    "PC lag memory leak": "RAM Upgrade",
    "RAM error on startup": "RAM Upgrade",
    "System memory low": "RAM Upgrade",
    "PC freeze heavy apps": "RAM Upgrade",
    "Laptop crash RAM issue": "RAM Upgrade",
    "RAM conflict problem": "RAM Upgrade",
    "PC slow after sleep": "RAM Upgrade",
    "RAM not compatible": "RAM Upgrade",
    "PC restart under load": "RAM Upgrade",
    "Laptop boot fail RAM": "RAM Upgrade",
    "Memory issue windows": "RAM Upgrade",
    "PC crash random": "RAM Upgrade",
    "RAM overuse problem": "RAM Upgrade",
    "PC stutter memory": "RAM Upgrade",
    "RAM error blue screen": "Blue Screen (BSOD)",
    "PC lag memory": "RAM Upgrade",
    "Laptop freeze multitask": "RAM Upgrade",
    "PC memory spike": "RAM Upgrade",
    "RAM fail boot": "RAM Upgrade",
    "System unstable RAM": "RAM Upgrade",
    "PC hang open software": "RAM Upgrade",
    "Laptop restart RAM": "RAM Upgrade",
    "RAM slot dead": "RAM Upgrade",
    "PC not start RAM": "RAM Upgrade",
    "Memory corrupted": "RAM Upgrade",
    
    # STORAGE / HDD / SSD (181-240)
    "PC slow opening files": "SSD Upgrade",
    "Windows not loading": "Windows Boot Failure",
    "Disk full always": "SSD Upgrade",
    "PC not boot after SSD": "SSD Upgrade",
    "Hard disk noise": "SSD Upgrade",
    "PC freeze file copy": "SSD Upgrade",
    "Storage not showing": "SSD Upgrade",
    "Disk error message": "SSD Upgrade",
    "PC stuck loading windows": "SSD Upgrade",
    "Boot device not found": "Windows Boot Failure",
    "HDD making sound": "SSD Upgrade",
    "SSD not detected": "SSD Upgrade",
    "PC crash disk use": "SSD Upgrade",
    "Storage disappear suddenly": "SSD Upgrade",
    "PC slow disk usage": "SSD Upgrade",
    "Laptop not boot SSD": "SSD Upgrade",
    "Disk read error": "SSD Upgrade",
    "Windows stuck loading disk": "SSD Upgrade",
    "PC freeze disk access": "SSD Upgrade",
    "Hard drive fail maybe": "SSD Upgrade",
    "SSD slow issue": "SSD Upgrade",
    "Disk usage 100%": "SSD Upgrade",
    "Storage corrupted": "SSD Upgrade",
    "PC restart disk error": "SSD Upgrade",
    "Disk not accessible": "SSD Upgrade",
    "Laptop disk slow": "SSD Upgrade",
    "PC hang file open": "SSD Upgrade",
    "Windows disk error": "SSD Upgrade",
    "Disk partition missing": "SSD Upgrade",
    "PC slow boot disk": "SSD Upgrade",
    "HDD click sound": "SSD Upgrade",
    "Storage fail message": "SSD Upgrade",
    "PC freeze while install": "SSD Upgrade",
    "SSD boot fail": "SSD Upgrade",
    "Disk error startup": "SSD Upgrade",
    "PC slow with HDD": "SSD Upgrade",
    "Storage not readable": "SSD Upgrade",
    "PC crash file move": "SSD Upgrade",
    "Disk error blue screen": "SSD Upgrade",
    "Laptop disk overheating": "SSD Upgrade",
    "Storage lag issue": "SSD Upgrade",
    "PC disk corrupted": "SSD Upgrade",
    "Disk not formatted": "SSD Upgrade",
    "Windows disk problem": "SSD Upgrade",
    "HDD very slow": "SSD Upgrade",
    "SSD not boot": "SSD Upgrade",
    "PC stuck disk check": "SSD Upgrade",
    "Disk repair loop": "SSD Upgrade",
    "Storage error windows": "SSD Upgrade",
    "PC disk fail": "SSD Upgrade",
    "Laptop freeze disk": "SSD Upgrade",
    "Disk drive missing": "SSD Upgrade",
    "Hard disk error": "SSD Upgrade",
    "PC slow copy paste": "SSD Upgrade",
    "Disk bad sector": "SSD Upgrade",
    "Windows storage error": "SSD Upgrade",
    "Disk not mounting": "SSD Upgrade",
    "SSD not recognized": "SSD Upgrade",
    "PC freeze disk scan": "SSD Upgrade",
    "Storage failure": "SSD Upgrade",
    
    # NETWORK / INTERNET (241-300)
    "No internet on PC": "Wi-Fi Adapter Upgrade",
    "WiFi connected no internet": "Wi-Fi Adapter Upgrade",
    "Internet slow only PC": "Wi-Fi Adapter Upgrade",
    "Ethernet not working": "Wi-Fi Adapter Upgrade",
    "Network icon missing": "Wi-Fi Adapter Upgrade",
    "WiFi disconnect always": "Wi-Fi Adapter Upgrade",
    "Internet stop suddenly": "Wi-Fi Adapter Upgrade",
    "PC not detect WiFi": "Wi-Fi Adapter Upgrade",
    "Network error message": "Wi-Fi Adapter Upgrade",
    "Internet work phone not PC": "Wi-Fi Adapter Upgrade",
    "WiFi very slow PC": "Wi-Fi Adapter Upgrade",
    "Ethernet cable not detect": "Wi-Fi Adapter Upgrade",
    "Network driver missing": "Driver Issue",
    "PC no network access": "Wi-Fi Adapter Upgrade",
    "Internet drop randomly": "Wi-Fi Adapter Upgrade",
    "PC can't browse internet": "Wi-Fi Adapter Upgrade",
    "WiFi signal weak PC": "Wi-Fi Adapter Upgrade",
    "Network adapter error": "Wi-Fi Adapter Upgrade",
    "PC internet unstable": "Wi-Fi Adapter Upgrade",
    "Laptop no WiFi": "Wi-Fi Adapter Upgrade",
    "Ethernet connected no net": "Wi-Fi Adapter Upgrade",
    "Network reset issue": "Wi-Fi Adapter Upgrade",
    "PC internet limited": "Wi-Fi Adapter Upgrade",
    "WiFi keeps disconnect": "Wi-Fi Adapter Upgrade",
    "Network not available": "Wi-Fi Adapter Upgrade",
    "PC slow internet": "Wi-Fi Adapter Upgrade",
    "Internet error windows": "Wi-Fi Adapter Upgrade",
    "Laptop network issue": "Wi-Fi Adapter Upgrade",
    "PC no IP address": "Wi-Fi Adapter Upgrade",
    "Network problem after update": "Driver Issue",
    "WiFi not turning on": "Wi-Fi Adapter Upgrade",
    "Ethernet slow speed": "Wi-Fi Adapter Upgrade",
    "PC DNS error": "Wi-Fi Adapter Upgrade",
    "Internet page not load": "Wi-Fi Adapter Upgrade",
    "Network driver problem": "Driver Issue",
    "PC internet crash": "Wi-Fi Adapter Upgrade",
    "Laptop WiFi missing": "Wi-Fi Adapter Upgrade",
    "Network problem only PC": "Wi-Fi Adapter Upgrade",
    "WiFi connect disconnect": "Wi-Fi Adapter Upgrade",
    "PC offline always": "Wi-Fi Adapter Upgrade",
    "Ethernet not recognized": "Wi-Fi Adapter Upgrade",
    "Internet unstable PC": "Wi-Fi Adapter Upgrade",
    "Network adapter missing": "Wi-Fi Adapter Upgrade",
    "PC can't connect WiFi": "Wi-Fi Adapter Upgrade",
    "Internet timeout error": "Wi-Fi Adapter Upgrade",
    "Laptop slow network": "Wi-Fi Adapter Upgrade",
    "PC net error": "Wi-Fi Adapter Upgrade",
    "Network disconnected message": "Wi-Fi Adapter Upgrade",
    "PC internet drop": "Wi-Fi Adapter Upgrade",
    "WiFi error PC": "Wi-Fi Adapter Upgrade",
    "Network not working": "Wi-Fi Adapter Upgrade",
    "PC no internet access": "Wi-Fi Adapter Upgrade",
    "Laptop internet fail": "Wi-Fi Adapter Upgrade",
    "Ethernet cable issue": "Wi-Fi Adapter Upgrade",
    "PC can't connect router": "Wi-Fi Adapter Upgrade",
    "Network problem windows": "Wi-Fi Adapter Upgrade",
    "Internet error only PC": "Wi-Fi Adapter Upgrade",
    "WiFi not found": "Wi-Fi Adapter Upgrade",
    "Network fail startup": "Wi-Fi Adapter Upgrade",
    "Internet not responding": "Wi-Fi Adapter Upgrade",
    
    # GRAPHICS / DISPLAY (301-360)
    "Screen black PC on": "No Display / No Signal",
    "Display flickering": "Monitor Issue",
    "Lines on screen": "Monitor Issue",
    "Screen white suddenly": "Monitor Issue",
    "PC restart gaming": "GPU Overheat",
    "Game lag graphics": "GPU Upgrade",
    "Display driver error": "Driver Issue",
    "Monitor no signal": "No Display / No Signal",
    "PC heat gaming": "GPU Overheat",
    "Graphics card not detect": "GPU Upgrade",
    "Screen resolution wrong": "Driver Issue",
    "PC crash open game": "GPU Overheat",
    "Display freeze": "Monitor Issue",
    "Laptop screen black": "No Display / No Signal",
    "PC display glitch": "Monitor Issue",
    "Graphics error windows": "Driver Issue",
    "Screen tearing issue": "GPU Upgrade",
    "Low FPS problem": "GPU Upgrade",
    "PC crash GPU": "GPU Overheat",
    "Monitor flicker random": "Monitor Issue",
    "Display color wrong": "Monitor Issue",
    "Laptop screen dim": "Monitor Issue",
    "PC no display HDMI": "No Display / No Signal",
    "Screen blink issue": "Monitor Issue",
    "Graphics driver fail": "Driver Issue",
    "PC restart graphics load": "GPU Overheat",
    "Screen artifacts": "GPU Upgrade",
    "GPU overheating": "GPU Overheat",
    "Display lag problem": "GPU Upgrade",
    "PC no display VGA": "No Display / No Signal",
    "Screen blurry": "Monitor Issue",
    "Laptop graphics slow": "GPU Upgrade",
    "PC display cut": "Monitor Issue",
    "Monitor not detected": "No Display / No Signal",
    "Screen flash issue": "Monitor Issue",
    "Graphics crash error": "GPU Overheat",
    "PC freeze gaming": "GPU Overheat",
    "GPU fan loud": "GPU Overheat",
    "Screen not full": "Driver Issue",
    "Display scaling issue": "Driver Issue",
    "PC black screen boot": "No Display / No Signal",
    "Laptop flicker screen": "Monitor Issue",
    "GPU not working": "GPU Upgrade",
    "Display error startup": "Driver Issue",
    "Screen color issue": "Monitor Issue",
    "Graphics lag windows": "GPU Upgrade",
    "PC no signal display": "No Display / No Signal",
    "Laptop screen glitch": "Monitor Issue",
    "GPU driver missing": "Driver Issue",
    "Display refresh issue": "Driver Issue",
    "PC crash render": "GPU Overheat",
    "Screen resolution reset": "Driver Issue",
    "Monitor display issue": "Monitor Issue",
    "Graphics stutter": "GPU Upgrade",
    "Screen ghosting": "Monitor Issue",
    "PC display lag": "GPU Upgrade",
    "GPU crash gaming": "GPU Overheat",
    "Screen pixel issue": "Monitor Issue",
    "Display driver stop": "Driver Issue",
    "Monitor no picture": "No Display / No Signal",
    
    # HEAT / FAN / HARDWARE + COMMON (361-500)
    "PC very hot": "CPU Overheat",
    "Fan very loud": "CPU Overheat",
    "PC shutdown heat": "CPU Overheat",
    "CPU overheat warning": "CPU Overheat",
    "Laptop heat too much": "CPU Overheat",
    "Fan not spinning": "CPU Overheat",
    "PC slow when hot": "CPU Overheat",
    "Temperature high always": "CPU Overheat",
    "PC off gaming": "GPU Overheat",
    "Laptop overheating": "CPU Overheat",
    "PC fan noise": "CPU Overheat",
    "System thermal issue": "CPU Overheat",
    "CPU temp high": "CPU Overheat",
    "Laptop heat shutdown": "CPU Overheat",
    "Fan speed high": "CPU Overheat",
    "PC warm idle": "CPU Overheat",
    "Cooling problem PC": "CPU Overheat",
    "Laptop fan not work": "CPU Overheat",
    "PC temp spike": "CPU Overheat",
    "System overheat error": "CPU Overheat",
    "PC heat summer": "CPU Overheat",
    "Laptop burn hot": "CPU Overheat",
    "Fan broken maybe": "CPU Overheat",
    "PC air flow bad": "CPU Overheat",
    "System hot slow": "CPU Overheat",
    "PC cooling issue": "CPU Overheat",
    "Fan vibration noise": "CPU Overheat",
    "Laptop heat lag": "CPU Overheat",
    "CPU fan error": "CPU Overheat",
    "PC hot shutdown": "CPU Overheat",
    "System temp alert": "CPU Overheat",
    "Fan dust problem": "CPU Overheat",
    "Laptop thermal issue": "CPU Overheat",
    "PC fan stop": "CPU Overheat",
    "CPU heat warning": "CPU Overheat",
    "System overheating": "CPU Overheat",
    "PC temp abnormal": "CPU Overheat",
    "Laptop heat problem": "CPU Overheat",
    "PC cooling fail": "CPU Overheat",
    "Fan noisy always": "CPU Overheat",
    "PC blue screen": "Blue Screen (BSOD)",
    "Windows crash suddenly": "Blue Screen (BSOD)",
    "PC stuck restart": "Windows Boot Failure",
    "Error on startup": "Windows Boot Failure",
    "PC not shutdown": "Windows Boot Failure",
    "Windows update fail": "Windows Boot Failure",
    "Driver problem error": "Driver Issue",
    "PC stuck logo": "Windows Boot Failure",
    "System corrupted message": "OS Reinstall / Corrupted",
    "Something wrong PC": "General Repair",
    "PC error popup": "General Repair",
    "Windows not responding": "Slow Performance",
    "PC crash random": "General Repair",
    "Laptop freeze sudden": "Slow Performance",
    "PC problem unknown": "General Repair",
    "System error message": "General Repair",
    "PC fail update": "Windows Boot Failure",
    "Windows repair loop": "Windows Boot Failure",
    "PC software error": "General Repair",
    "Laptop crash often": "General Repair",
    "PC system fail": "General Repair",
    "Error code show": "General Repair",
    "PC malfunction": "General Repair",
    "Windows problem detected": "General Repair",
    "PC need repair": "General Repair",
    "Laptop error message": "General Repair",
    "System fail boot": "Windows Boot Failure",
    "PC issue always": "General Repair",
    "Windows error screen": "Blue Screen (BSOD)",
    "PC system issue": "General Repair",
    "Laptop OS error": "OS Reinstall / Corrupted",
    "PC error startup": "Windows Boot Failure",
    "System not stable": "General Repair",
    "PC crash boot": "Windows Boot Failure",
    "Windows problem again": "General Repair",
    "Laptop OS fail": "OS Reinstall / Corrupted",
    "PC system slow error": "Slow Performance",
    "Error after install": "General Repair",
    "PC stuck error": "Windows Boot Failure",
    "Windows failure": "Windows Boot Failure",
    "Laptop system crash": "General Repair",
    "PC problem sudden": "General Repair",
    "OS error message": "OS Reinstall / Corrupted",
    "PC malfunction error": "General Repair",
    "Windows fail load": "Windows Boot Failure",
    "Laptop error boot": "Windows Boot Failure",
    "PC system corrupted": "OS Reinstall / Corrupted",
    "Error message pop": "General Repair",
    "Windows not start": "Windows Boot Failure",
    "Laptop OS issue": "OS Reinstall / Corrupted",
    "PC unknown error": "General Repair",
    "System error boot": "Windows Boot Failure",
    "PC failure detected": "General Repair",
    "Windows crash loop": "Blue Screen (BSOD)",
    "Laptop startup error": "Windows Boot Failure",
    "PC system failure": "General Repair",
    "Error when start": "Windows Boot Failure",
    "PC OS crash": "OS Reinstall / Corrupted",
    "Windows error popup": "General Repair",
    "Laptop system issue": "General Repair",
    "PC boot error": "Windows Boot Failure",
    "System error detected": "General Repair",
    "PC error loop": "Windows Boot Failure",
    "Windows system fail": "Windows Boot Failure",
    "Laptop error screen": "Blue Screen (BSOD)",
    "PC not working": "General Repair",
    "System broken maybe": "General Repair",
    "PC always error": "General Repair",
    "Windows stuck problem": "Windows Boot Failure",
    "Laptop OS crash": "OS Reinstall / Corrupted",
    "PC need fixing": "General Repair",
    "System issue message": "General Repair",
    "PC not normal": "General Repair",
    "Windows problem again": "General Repair",
    "Laptop fail boot": "Windows Boot Failure",
    "PC crash error": "General Repair",
    "System error always": "General Repair",
    "PC issue startup": "Windows Boot Failure",
    "Windows fail again": "Windows Boot Failure",
    "Laptop broken system": "OS Reinstall / Corrupted",
    "PC error detected": "General Repair",
    "OS not working": "OS Reinstall / Corrupted",
    "PC stuck error screen": "Windows Boot Failure",
    "System fault message": "General Repair",
    "Laptop system fail": "General Repair",
    "PC problem startup": "Windows Boot Failure",
    "Windows OS error": "OS Reinstall / Corrupted",
    "PC broken software": "General Repair",
    "System error occur": "General Repair",
    "Laptop OS broken": "OS Reinstall / Corrupted",
    "PC fail system": "General Repair",
    "Windows crash error": "Blue Screen (BSOD)",
    "PC always crash": "General Repair",
    "System error boot": "Windows Boot Failure",
    "Laptop system broken": "OS Reinstall / Corrupted",
    "PC problem detected": "General Repair",
    "OS error startup": "OS Reinstall / Corrupted",
    "PC fault detected": "General Repair",
    "Windows fail system": "Windows Boot Failure",
    "My PC not working properly": "General Repair",
}


def test_model():
    """Test the error detection model on real-world issues."""
    print("=" * 80)
    print("TESTING ERROR DETECTION MODEL ON REAL-WORLD ISSUES")
    print("=" * 80)
    
    # Import detection function
    try:
        from app import detect_error_type_hybrid
    except ImportError:
        print("[ERROR] Could not import detect_error_type_hybrid")
        print("Make sure you're running this from the backend directory")
        return
    
    results = []
    correct = 0
    incorrect = 0
    
    for issue, expected in REAL_WORLD_ISSUES.items():
        try:
            result = detect_error_type_hybrid(issue)
            predicted = result.get('label')
            confidence = result.get('confidence', 0.0)
            source = result.get('source', 'unknown')
            
            is_correct = predicted == expected
            if is_correct:
                correct += 1
            else:
                incorrect += 1
            
            results.append({
                'issue': issue,
                'expected': expected,
                'predicted': predicted,
                'confidence': confidence,
                'source': source,
                'correct': is_correct
            })
            
        except Exception as e:
            print(f"[ERROR] Failed to process: {issue} - {e}")
            incorrect += 1
            results.append({
                'issue': issue,
                'expected': expected,
                'predicted': None,
                'confidence': 0.0,
                'source': 'error',
                'correct': False
            })
    
    # Calculate accuracy
    total = len(results)
    accuracy = (correct / total) * 100 if total > 0 else 0
    
    print(f"\n{'='*80}")
    print(f"RESULTS")
    print(f"{'='*80}")
    print(f"Total Issues Tested: {total}")
    print(f"Correct Predictions: {correct}")
    print(f"Incorrect Predictions: {incorrect}")
    print(f"Accuracy: {accuracy:.2f}%")
    
    # Show incorrect predictions
    incorrect_results = [r for r in results if not r['correct']]
    if incorrect_results:
        print(f"\n{'='*80}")
        print(f"INCORRECT PREDICTIONS ({len(incorrect_results)})")
        print(f"{'='*80}")
        for r in incorrect_results[:20]:  # Show first 20
            print(f"\nIssue: {r['issue']}")
            print(f"  Expected: {r['expected']}")
            print(f"  Predicted: {r['predicted']} (confidence: {r['confidence']:.2f}, source: {r['source']})")
        
        if len(incorrect_results) > 20:
            print(f"\n... and {len(incorrect_results) - 20} more incorrect predictions")
    
    # Save results to JSON
    output_file = HERE / "real_world_test_results.json"
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump({
            'summary': {
                'total': total,
                'correct': correct,
                'incorrect': incorrect,
                'accuracy': accuracy
            },
            'results': results
        }, f, indent=2, ensure_ascii=False)
    
    print(f"\n{'='*80}")
    print(f"Results saved to: {output_file}")
    print(f"{'='*80}")
    
    return results, accuracy


if __name__ == "__main__":
    test_model()

